### ISSUE TITLE
Add documentation / prefab on how to properly use PlatformDeviceAssociation  with object state switcher

### ISSUE THREAD

**Issue by studentutu** [ExtendRealityLtd/Tilia.Utilities.ObjectStateSwitcher.Unity#34]
It would be nice to have some sort of prefab on how to auto-enable target SDK rig (depending on the currently found HMD). It is even better if you could put a prefab for Oculus in there.

**Comment by fight4dream** [comment]
The components involved are PlatformDeviceAssociation and GameObjectsAssociationActivator
Reviewer please move this request to suitable repo
